services:
  - type: web
    name: welding-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backendServer.wsgi
    envVars:
      - key: SECRET_KEY
        value: django-insecure--^0p5&9_6zwtma@_8ocqf4w50=sdj%t+4urw#!%*!v^+53u(5s
      - key: CLOUDINARY_URL
        value: cloudinary://<your_api_key>:<your_api_secret>@dfnbvtqae
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
    staticPublishPath: staticfiles
