services:
  - type: web
    name: welding-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backendServer.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: welding-db
          property: connectionString
      - key: CLOUDINARY_URL
        value: cloudinary://<your_api_key>:<your_api_secret>@dfnbvtqae
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: EMAIL_HOST_USER
        value: tejavendra2006@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-gmail-app-password
      - key: EMAIL_RECEIVER
        value: tejavendra2006@gmail.com
