# Generated by Django 5.2.4 on 2025-07-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_designorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designorder',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
